Traceback (most recent call last):
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import pandas as pd
import gsw 
import numpy as np
import xarray as xr
import os
import pycnv

from matplotlib.ticker import ScalarFormatter
from seabird.cnv import fCNV
from seabird.netcdf import cnv2nc
from datetime import datetime
#from modules.nsq import adiabatic_leveling
import mixsea as mx
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 7[0m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mxarray[39;00m [38;5;28;01mas[39;00m [38;5;21;01mxr[39;00m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[0;32m----> 7[0m [38;5;28;01mimport[39;00m [38;5;21;01mpycnv[39;00m
[1;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mticker[39;00m [38;5;28;01mimport[39;00m ScalarFormatter
[1;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mseabird[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcnv[39;00m [38;5;28;01mimport[39;00m fCNV

[0;31mModuleNotFoundError[0m: No module named 'pycnv'

