Traceback (most recent call last):
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Plot the fields
# choose the index of the snapshot to show
itime = 0
map1 = winter_flux.lhtfl[itime,:,:]

fig, axs = plt.subplots(2,2)
axs[0,0].contourf(data1.lon, data1.lat, map1, cmap='RdYlBu')
axs[0,0].set_title('Latent heat flux')
axs[0,0].set_ylabel('Latitude')

# Cumbersome date time to string
d = data1.time[itime].dt.strftime('%Y').values
fig.suptitle('NCEP Reanalysis \n' + d + 'winter')

fig.savefig('fig1-Lastname-heatflux.png')

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[10], line 4[0m
[1;32m      1[0m [38;5;66;03m# Plot the fields[39;00m
[1;32m      2[0m [38;5;66;03m# choose the index of the snapshot to show[39;00m
[1;32m      3[0m itime [38;5;241m=[39m [38;5;241m0[39m
[0;32m----> 4[0m map1 [38;5;241m=[39m [43mwinter_flux[49m[38;5;241m.[39mlhtfl[itime,:,:]
[1;32m      6[0m fig, axs [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m2[39m,[38;5;241m2[39m)
[1;32m      7[0m axs[[38;5;241m0[39m,[38;5;241m0[39m][38;5;241m.[39mcontourf(data1[38;5;241m.[39mlon, data1[38;5;241m.[39mlat, map1, cmap[38;5;241m=[39m[38;5;124m'[39m[38;5;124mRdYlBu[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'winter_flux' is not defined

